### ISSUE TITLE
Want to Add my Web Project

### ISSUE THREAD

**Issue by anubhav201241** [Design-and-Code/Projects-showcase#11]
Hey, @DevrajDC I want to contribute my web project to your repository kindly assign this issue to me

**Comment by DevrajDC** [comment]
Sure go ahead! Just follow the file structure given in the readme.md

**Comment by lostgirljourney** [comment]
@DevrajDC close?

**Comment by DevrajDC** [comment]
> @DevrajDC close?

did he add? i dont remember so many PRs I closed.

**Comment by lostgirljourney** [comment]
> > @DevrajDC close?
> 
> did he add? i dont remember so many PRs I closed.

![image](https://user-images.githubusercontent.com/56036475/135611746-a3de9aee-0117-41da-ba32-172e0accaa86.png)
