### ISSUE TITLE
Add Contributing.md for contributors

### ISSUE THREAD

**Issue by Greeshma2903** [Design-and-Code/Projects-showcase#26]
I noticed that it can be a little confusing for contributors to add their projects to the repo. 
Creating a Contributing.MD will be helpful.

What do I plan to add?
- Folder path and naming that contributors should follow
- Naming convention to be followed

**Comment by OctoplusNinja** [comment]
assigned to you @Greeshma2903 !!

**Comment by lostgirljourney** [comment]
@Greeshma2903 do it asap. 😄

**Comment by lostgirljourney** [comment]
@Greeshma2903 if done, close the PR.
