### ISSUE TITLE
Creating a 3D digital card payment UI Prototype

### ISSUE THREAD

**Issue by NerdyVisky** [Design-and-Code/Projects-showcase#34]
# Aim 
To design a credit/debit card payment front-end gateway with 3D card-flip and animations using open-source js libraries.

# Technologies to be used
HTML5, SASS, JS and JS libraries.

# Screenshots
![](https://docs.google.com/uc?id=1myp0uZFkQHNWIVghNAWsmDiQXrRgzHvW)

![](https://docs.google.com/uc?id=14YglJ8lin4VZzBhmixmVzzbBx6dNQhO7)

![](https://docs.google.com/uc?id=1FBqDhtLu55Cvfm0zUhm-OCz_gqxVpmOv)

![](https://docs.google.com/uc?id=1o3K0DEc0HDs6cugl8-VAp2T35RIhrQcX)

**Comment by OctoplusNinja** [comment]
Assigned you @NerdyVisky 🚀

**Comment by DevrajDC** [comment]
The project has been merged, so closing this Issue! If you haven't joined the community then join here: https://discord.gg/druweDMn3s
